name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Tag
        id: vars
        run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.vars.outputs.tag }} .

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.vars.outputs.tag }}